name: graduation_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.9.0
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.2
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  geolocator: ^14.0.1
  get: ^4.7.2
  gradient_borders: ^1.0.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  localstorage: ^6.0.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  supabase_auth_ui: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/screens/home.png
    - assets/product.jpg
    - assets/filterIcon.png
flutter_assets:
  assets_path: assets/
  output_path: lib/core/core/assets/genImages/
  filename: imageAssets.dart
  field_prefix: resource
  ignore_comments: true