name: graduation_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.9.0
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.2
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  geolocator: ^14.0.1
  get: ^4.7.2
  gradient_borders: ^1.0.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  localstorage: ^6.0.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  supabase_auth_ui: ^0.5.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.1
  firebase_analytics: ^11.3.2
  firebase_crashlytics: ^4.1.3
  crypto: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Screens/home.png
    - assets/Screens/heart.png
    - assets/Screens/gift.png
    - assets/Screens/sheet-plastic.png
    - assets/product.jpg
    - assets/filterIcon.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png
    - assets/pharmacy_logo.png
flutter_assets:
  assets_path: assets/
  output_path: lib/core/core/assets/genImages/
  filename: imageAssets.dart
  field_prefix: resource
  ignore_comments: true