// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabbRBlmFpr-lEt2WpPOBUU4WXFzM96PA',
    appId: '1:538056277715:web:641dd2ed70f93c89969e26',
    messagingSenderId: '538056277715',
    projectId: 'online-pharmacy-ed15c',
    authDomain: 'online-pharmacy-ed15c.firebaseapp.com',
    storageBucket: 'online-pharmacy-ed15c.firebasestorage.app',
    measurementId: 'G-GK2ZHFX4LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmCM4aufpgSILOGvuew5Ggw5UW6A2ziXE',
    appId: '1:538056277715:android:be0d5f3f5300d324969e26',
    messagingSenderId: '538056277715',
    projectId: 'online-pharmacy-ed15c',
    storageBucket: 'online-pharmacy-ed15c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwv0UMxfIGGhzfLpDb1tmEiuU8mTZGrOo',
    appId: '1:538056277715:ios:c4a10930ccc129c5969e26',
    messagingSenderId: '538056277715',
    projectId: 'online-pharmacy-ed15c',
    storageBucket: 'online-pharmacy-ed15c.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwv0UMxfIGGhzfLpDb1tmEiuU8mTZGrOo',
    appId: '1:538056277715:ios:c4a10930ccc129c5969e26',
    messagingSenderId: '538056277715',
    projectId: 'online-pharmacy-ed15c',
    storageBucket: 'online-pharmacy-ed15c.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBabbRBlmFpr-lEt2WpPOBUU4WXFzM96PA',
    appId: '1:538056277715:web:dd4b7f5a60f78c7c969e26',
    messagingSenderId: '538056277715',
    projectId: 'online-pharmacy-ed15c',
    authDomain: 'online-pharmacy-ed15c.firebaseapp.com',
    storageBucket: 'online-pharmacy-ed15c.firebasestorage.app',
    measurementId: 'G-FNNHK2D165',
  );
}
